### ISSUE TITLE
ValueError: Number of processes must be at least 1

### ISSUE THREAD

**Issue by francicco** [RosettaCommons/RoseTTAFold#107]
Hi,

I'm having this type of error, not always. I don't understand the reason why.
Any help?
Thanks a lot!
F

```
(folding) [tk19812@bp1-login01 Eueides_Etal.Etal0000684G814b.5]$ python -u -W ignore /user/work/tk19812/software/RoseTTAFold-1.1.0/DAN-msa/pick_final_models.div.py pdb-3track model 28
Traceback (most recent call last):
  File "/user/work/tk19812/software/RoseTTAFold-1.1.0/DAN-msa/pick_final_models.div.py", line 113, in <module>
    pool = mp.Pool(n_core_pool)
  File "/user/home/tk19812/.conda/envs/folding/lib/python3.7/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/user/home/tk19812/.conda/envs/folding/lib/python3.7/multiprocessing/pool.py", line 169, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
```

**Comment by Geraldene** [comment]
I am facing the same issue, did you find a way around this @francicco

**Comment by francicco** [comment]
Hi @Geraldene,

I deleted all files and re-run the pipeline from scratch. It worked.
Cheers
F

**Comment by gchrsnbriggs** [comment]
Running into the same issue on a cluster. When the files are deleted we run into the same issue. The cluster is allocating 8 cores and 32 GB RAM but the code is not detecting it and reporting the same error code.

**Comment by abxka** [comment]
There have been changes in the Rosetta Codebase, which did not make it to Pyrosetta. In my case, in 

`RoseTTAFold/DAN-msa/pyErrorPred/featurize.py`

there were two function calls to navigate through the energy graph that do not exist in Rosetta anymore. 

On line 80, I replaced 
`iru.__mul__()` 
with 
`iru.dereference()`

And in line 102, I replaced 
`iru.plus_plus()`
with
`iru.pre_increment()`

The code works for me now.

**Comment by jayakajaeha** [comment]
Hello, @abxka I followed your instruction.

However, then i got new error like this:

```
/bin/sh: 1: /bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found/mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found

/bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found
/bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found
/bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found
/bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found
/bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found
/bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found
/bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found
/bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found
/bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found
/bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found
/bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found/bin/sh: 1: 
/mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found
/bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found
/bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found
/bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found
/bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found
/bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found
/bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found
/bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ypkim/miniconda3/envs/folding/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/ypkim/miniconda3/envs/folding/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/mnt/D/RoseTTAFold-1.1.0/DAN-msa/pick_final_models.div.py", line 72, in calc_lddt_dist
    lddt_1 = float(os.popen("%s/lddt/lddt -c %s %s | grep Glob"%(script_dir, pose_i, pose_j)).readlines()[-1].split()[-1])
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/D/RoseTTAFold-1.1.0/DAN-msa/pick_final_models.div.py", line 114, in <module>
    raw_dist = pool.map(calc_lddt_dist, args)
  File "/home/ypkim/miniconda3/envs/folding/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/ypkim/miniconda3/envs/folding/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
IndexError: list index out of range
```
can you help me to solve this problem?
Or is there anyone can solve this problem?

Thank you.

**Comment by roccomoretti** [comment]
@jayyoonakajaeha `/bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found`  looks to be the issue.

It's trying to use the lddt application to do some computations, but for some reason lddt is not installed in your environment.

When you ran the `install_dependencies.sh` script, it may not have worked properly. (Note that you'll need internet access from the computer you're running it on.)

**Comment by marcosjviana** [comment]
> There have been changes in the Rosetta Codebase, which did not make it to Pyrosetta. In my case, in
> 
> `RoseTTAFold/DAN-msa/pyErrorPred/featurize.py`
> 
> there were two function calls to navigate through the energy graph that do not exist in Rosetta anymore.
> 
> On line 80, I replaced `iru.__mul__()` with `iru.dereference()`
> 
> And in line 102, I replaced `iru.plus_plus()` with `iru.pre_increment()`
> 
> The code works for me now.

Thank you, worked for me!
