### ISSUE TITLE
ValueError: Number of processes must be at least 1

### ISSUE THREAD

**Issue by wonyoungtae** [RosettaCommons/RoseTTAFold#141]
When I attempted to use RoseTTAFold, I encountered the following error at the end.

```
$ nano /log/pick.stderr

Traceback (most recent call last):
  File "/home/yt/RoseTTAFold/DAN-msa/pick_final_models.div.py", line 113, in <module>
    pool = mp.Pool(n_core_pool)
  File "/home/yt/anaconda3/envs/folding/lib/python3.7/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/home/yt/anaconda3/envs/folding/lib/python3.7/multiprocessing/pool.py", line 169, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
```

How can I solve this problem?

**Comment by supernova4869** [comment]
Seems caused of the conflicts among python 3.7, tensorflow, numpy, and so on. Same as #135

**Comment by jayakajaeha** [comment]
Hello, I did the following instruction.
[#135]

However, then i got new error like this:

```
/bin/sh: 1: /bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found/mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found

/bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found
/bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found
/bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found
/bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found
/bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found
/bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found
/bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found
/bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found
/bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found
/bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found
/bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found/bin/sh: 1: 
/mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found
/bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found
/bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found
/bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found
/bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found
/bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found
/bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found
/bin/sh: 1: /mnt/D/RoseTTAFold-1.1.0/lddt/lddt: not found
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ypkim/miniconda3/envs/folding/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/ypkim/miniconda3/envs/folding/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/mnt/D/RoseTTAFold-1.1.0/DAN-msa/pick_final_models.div.py", line 72, in calc_lddt_dist
    lddt_1 = float(os.popen("%s/lddt/lddt -c %s %s | grep Glob"%(script_dir, pose_i, pose_j)).readlines()[-1].split()[-1])
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/D/RoseTTAFold-1.1.0/DAN-msa/pick_final_models.div.py", line 114, in <module>
    raw_dist = pool.map(calc_lddt_dist, args)
  File "/home/ypkim/miniconda3/envs/folding/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/ypkim/miniconda3/envs/folding/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
IndexError: list index out of range
```

Is there anyone can solve this problem?

Thank you.

**Comment by alanclayrichard** [comment]
#143 solved this issue for me. Install lddt using bioconda and then move the executable in folding/bin/ to a new directory in <RoseTTAFold direcory>/lddt/

The install dependencies does not fetch the lddt with wget anymore. It returns 404
