### ISSUE TITLE
OSError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by siahuat0727** [RosettaCommons/RoseTTAFold#48]
Hi, thank you very much for this awesome work!

I tried to do complex modeling, but I encountered the following error.

```
$ python network/predict_complex.py -i example/complex_modeling/filtered2.a3m -o complex -Ls 218 310
Using backend: pytorch
Traceback (most recent call last):
  File "network/predict_complex.py", line 8, in <module>
    from RoseTTAFoldModel  import RoseTTAFoldModule_e2e
  File "/home/shengfa/RoseTTAFold/network/RoseTTAFoldModel.py", line 4, in <module>
    from Attention_module_w_str import IterativeFeatureExtractor
  File "/home/shengfa/RoseTTAFold/network/Attention_module_w_str.py", line 9, in <module>
    from InitStrGenerator import InitStr_Network
  File "/home/shengfa/RoseTTAFold/network/InitStrGenerator.py", line 6, in <module>
    import torch_geometric
  File "/home/shengfa/anaconda3/envs/RoseTTAFold/lib/python3.8/site-packages/torch_geometric/__init__.py", line 5, in <module>
    import torch_geometric.data
  File "/home/shengfa/anaconda3/envs/RoseTTAFold/lib/python3.8/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/shengfa/anaconda3/envs/RoseTTAFold/lib/python3.8/site-packages/torch_geometric/data/data.py", line 8, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/home/shengfa/anaconda3/envs/RoseTTAFold/lib/python3.8/site-packages/torch_sparse/__init__.py", line 14, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
  File "/home/shengfa/.local/lib/python3.8/site-packages/torch/_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "/home/shengfa/anaconda3/envs/RoseTTAFold/lib/python3.8/ctypes/__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
```

I have installed the environment using the below script:

```
#   If your NVIDIA driver compatible with cuda11
conda env create -f RoseTTAFold-linux.yml
```

And the drivers are as follows:

```
$ nvidia-smi 
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.23.05    Driver Version: 455.23.05    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
```

```
$ conda list
# packages in environment at /home/shengfa/anaconda3/envs/RoseTTAFold:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    conda-forge
_openmp_mutex             4.5                       1_gnu  
biopython                 1.78             py38h497a2fe_2    conda-forge
blas                      1.0                         mkl    conda-forge
blast-legacy              2.2.26                        2    biocore
brotlipy                  0.7.0           py38h497a2fe_1001    conda-forge
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2021.5.25            h06a4308_1  
certifi                   2021.5.30        py38h06a4308_0  
cffi                      1.14.5           py38ha65f79e_0    conda-forge
chardet                   3.0.4                    pypi_0    pypi
cryptography              3.4.7            py38ha5dfef3_0    conda-forge
cudatoolkit               11.1.74              h6bb024c_0    nvidia
decorator                 4.4.2                    pypi_0    pypi
dgl-cu110                 0.6.1                    pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
freetype                  2.10.4               h5ab3b9f_0  
gmp                       6.2.1                h2531618_2  
gnutls                    3.6.15               he1e5248_0  
googledrivedownloader     0.4                pyhd3deb0d_1    conda-forge
hhsuite                   3.3.0           py38pl5262hc37a69a_2    bioconda
idna                      2.10               pyh9f0ad1d_0    conda-forge
intel-openmp              2021.2.0           h06a4308_610  
jinja2                    3.0.1              pyhd8ed1ab_0    conda-forge
joblib                    1.0.1              pyhd8ed1ab_0    conda-forge
jpeg                      9b                   h024ee3a_2  
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.35.1               h7274673_9  
libblas                   3.9.0                     9_mkl    conda-forge
libcblas                  3.9.0                     9_mkl    conda-forge
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgfortran-ng            7.5.0               h14aa051_19    conda-forge
libgfortran4              7.5.0               h14aa051_19    conda-forge
libgomp                   9.3.0               h5101ec6_17  
libiconv                  1.15                 h63c8f33_5  
libidn2                   2.3.1                h27cfd23_0  
liblapack                 3.9.0                     9_mkl    conda-forge
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.3.0               hd4cf53a_17  
libtasn1                  4.16.0               h27cfd23_0  
libtiff                   4.2.0                h85742a9_0  
libunistring              0.9.10               h27cfd23_0  
libuv                     1.40.0               h7b6447c_0  
libwebp-base              1.2.0                h27cfd23_0  
lie-learn                 0.0.1.post1              pypi_0    pypi
lz4-c                     1.9.3                h2531618_0  
markupsafe                2.0.1            py38h497a2fe_0    conda-forge
mkl                       2021.2.0           h06a4308_296  
mkl-service               2.3.0            py38h27cfd23_1  
mkl_fft                   1.3.0            py38h42c9631_2  
mkl_random                1.2.1            py38ha9443f7_2  
ncurses                   6.2                  he6710b0_1  
nettle                    3.7.3                hbbd107a_1  
networkx                  2.5                        py_0    conda-forge
ninja                     1.10.2               hff7bd54_1  
numpy                     1.20.2           py38h2d18471_0  
numpy-base                1.20.2           py38hfae3a4d_0  
olefile                   0.46                       py_0    conda-forge
openh264                  2.1.0                hd408876_0  
openssl                   1.1.1k               h27cfd23_0  
packaging                 20.9               pyhd3eb1b0_0  
pandas                    1.2.5            py38h1abd341_0    conda-forge
perl                      5.26.2            h36c2ea0_1008    conda-forge
pillow                    8.2.0            py38he98fc37_0  
pip                       21.1.3           py38h06a4308_0  
psipred                   4.01                          1    biocore
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyrosetta                 2021.29+release.d8f55669792          pypi_0    pypi
pysocks                   1.7.1            py38h578d9bd_3    conda-forge
python                    3.8.10               h12debd9_8  
python-dateutil           2.8.1                      py_0    conda-forge
python-louvain            0.15               pyhd3deb0d_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytorch                   1.9.0           py3.8_cuda11.1_cudnn8.0.5_0    pytorch
pytorch-cluster           1.5.9           py38_torch_1.9.0_cu111    rusty1s
pytorch-geometric         1.7.2           py38_torch_1.9.0_cu111    rusty1s
pytorch-scatter           2.0.7           py38_torch_1.9.0_cu111    rusty1s
pytorch-sparse            0.6.10          py38_torch_1.9.0_cu111    rusty1s
pytorch-spline-conv       1.2.1           py38_torch_1.9.0_cu111    rusty1s
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
readline                  8.1                  h27cfd23_0  
requests                  2.25.1             pyhd3deb0d_0    conda-forge
scikit-learn              0.24.2           py38ha9443f7_0  
scipy                     1.7.0                    pypi_0    pypi
setuptools                52.0.0           py38h06a4308_0  
six                       1.16.0             pyhd3eb1b0_0  
sqlite                    3.36.0               hc218d9a_0  
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tk                        8.6.10               hbc83047_0  
torchaudio                0.9.0                      py38    pytorch
torchvision               0.10.0               py38_cu111    pytorch
tqdm                      4.61.1             pyhd8ed1ab_0    conda-forge
typing_extensions         3.10.0.0           pyh06a4308_0  
urllib3                   1.25.11                  pypi_0    pypi
wheel                     0.36.2             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.9                haebb681_0
```

Has anyone met the same error?
Thank you for any help you can offer.

**Comment by Github-bogar** [comment]
I also encountered this problem. It may be caused by the mismatch between the CUDA version and the pytoch version. First uninstall pytoch, and then reinstall the pytoch that conforms to your CUDA version, and then succeeded. Refer to the following articles:
http://www.zzvips.com/article/193757.html
