### ISSUE TITLE
predict short fragment ERROR

### ISSUE THREAD

**Issue by pfreezer** [RosettaCommons/RoseTTAFold#61]
Hello,

I want to use the codes to predict some short fragment (length 8), but the code cannot run with errors for both e2e 
and pyrosetta, the error came out at structure prediction stage with the message:

Using backend: pytorch
Traceback (most recent call last):
  File "/home/fpan/local/RoseTTAFold/network/predict_pyRosetta.py", line 200, in <module>
    pred.predict(args.a3m_fn, args.out_prefix, args.hhr, args.atab)
  File "/home/fpan/local/RoseTTAFold/network/predict_pyRosetta.py", line 86, in predict
    xyz_t, t1d, t0d = read_templates(L, ffdb, hhr_fn, atab_fn, n_templ=25)
  File "/home/fpan/local/RoseTTAFold/network/parsers.py", line 241, in read_templates
    xyz_t, qmap, t0d, t1d, ids = parse_templates(ffdb, hhr_fn, atab_fn)
  File "/home/fpan/local/RoseTTAFold/network/parsers.py", line 231, in parse_templates
    xyz = np.vstack(xyz).astype(np.float32)
  File "<__array_function__ internals>", line 5, in vstack
  File "/home/fpan/local/anaconda3/envs/RoseTTAFold/lib/python3.8/site-packages/numpy/core/shape_base.py", line 283, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: need at least one array to concatenate

Can anyone help me to deal with this problem?

**Comment by maymoona100** [comment]
You must have messed up the e2e .sh script.just give route to folders as  / weight, /pdb100, so on .and it will work well I faced the same error I resolved it this way
