### ISSUE TITLE
lddt folder problem

### ISSUE THREAD

**Issue by luckydogomg** [RosettaCommons/RoseTTAFold#62]
I check the Iddt folder, the folder is there but there is no file in it. 

Any help?

Thank you!

Error message:
cat pick.stderr 
/bin/sh: /lustre/work/dbecker/ymao/RoseTTAFold/lddt/lddt: No such file or directory
/bin/sh: /lustre/work/dbecker/ymao/RoseTTAFold/lddt/lddt: No such file or directory
/bin/sh: /lustre/work/dbecker/ymao/RoseTTAFold/lddt/lddt: No such file or directory
/bin/sh: /lustre/work/dbecker/ymao/RoseTTAFold/lddt/lddt: No such file or directory
/bin/sh: /lustre/work/dbecker/ymao/RoseTTAFold/lddt/lddt: No such file or directory
/bin/sh: /lustre/work/dbecker/ymao/RoseTTAFold/lddt/lddt: No such file or directory
/bin/sh: /lustre/work/dbecker/ymao/RoseTTAFold/lddt/lddt: No such file or directory
/bin/sh: /lustre/work/dbecker/ymao/RoseTTAFold/lddt/lddt: No such file or directory
/bin/sh: /lustre/work/dbecker/ymao/RoseTTAFold/lddt/lddt: No such file or directory
/bin/sh: /lustre/work/dbecker/ymao/RoseTTAFold/lddt/lddt: No such file or directory
/bin/sh: /lustre/work/dbecker/ymao/RoseTTAFold/lddt/lddt: No such file or directory
/bin/sh: /lustre/work/dbecker/ymao/RoseTTAFold/lddt/lddt: No such file or directory
/bin/sh: /lustre/work/dbecker/ymao/RoseTTAFold/lddt/lddt: No such file or directory
/bin/sh: /lustre/work/dbecker/ymao/RoseTTAFold/lddt/lddt: No such file or directory
/bin/sh: /lustre/work/dbecker/ymao/RoseTTAFold/lddt/lddt: No such file or directory
/bin/sh: /lustre/work/dbecker/ymao/RoseTTAFold/lddt/lddt: No such file or directory
/bin/sh: /lustre/work/dbecker/ymao/RoseTTAFold/lddt/lddt: No such file or directory
/bin/sh: /lustre/work/dbecker/ymao/RoseTTAFold/lddt/lddt: No such file or directory
/bin/sh: /lustre/work/dbecker/ymao/RoseTTAFold/lddt/lddt: No such file or directory
/bin/sh: /lustre/work/dbecker/ymao/RoseTTAFold/lddt/lddt: No such file or directory
/bin/sh: /lustre/work/dbecker/ymao/RoseTTAFold/lddt/lddt: No such file or directory
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/dbecker/ymao/.conda/envs/folding/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/dbecker/ymao/.conda/envs/folding/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/lustre/work/dbecker/ymao/RoseTTAFold/DAN-msa/pick_final_models.div.py", line 72, in calc_lddt_dist
    lddt_1 = float(os.popen("%s/lddt/lddt -c %s %s | grep Glob"%(script_dir, pose_i, pose_j)).readlines()[-1].split()[-1])
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/lustre/work/dbecker/ymao/RoseTTAFold/DAN-msa/pick_final_models.div.py", line 114, in <module>
    raw_dist = pool.map(calc_lddt_dist, args)
  File "/home/dbecker/ymao/.conda/envs/folding/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/dbecker/ymao/.conda/envs/folding/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
IndexError: list index out of range
"

**Comment by 275145** [comment]
@luckydogomg Have you solved this problem? I have the same problem, could you give me some advice?

**Comment by zyan-y** [comment]
For me, it was caused by install_dependencies.sh failing to download lddt.zip.
