### ISSUE TITLE
Run hhsearch have not "t000_.atab"

### ISSUE THREAD

**Issue by Meowooo** [RosettaCommons/RoseTTAFold#64]
detail:
Using backend: pytorch
Traceback (most recent call last):
  File "/data1/home/RoseTTAFold-main/network/predict_e2e.py", line 324, in <module>
    pred.predict(args.a3m_fn, args.out_prefix, args.hhr, args.atab)
  File "/data1/home/RoseTTAFold-main/network/predict_e2e.py", line 120, in predict
    xyz_t, t1d, t0d = read_templates(L, ffdb, hhr_fn, atab_fn, n_templ=10)
  File "/data1/home/RoseTTAFold-main/network/parsers.py", line 241, in read_templates
    xyz_t, qmap, t0d, t1d, ids = parse_templates(ffdb, hhr_fn, atab_fn)
  File "/data1/home/RoseTTAFold-main/network/parsers.py", line 180, in parse_templates
    for l in open(infile, "r").readlines():
FileNotFoundError: [Errno 2] No such file or directory: '/data1/home/RoseTTAFold-main/example/t000_.atab'

what should I do?

**Comment by minkbaek** [comment]
which hhsuite version are you using? could you give me more details?

**Comment by zliu36** [comment]
when I use the example and run **run_pyrosetta_ver.sh**, this code can create **t000_.ss2** ,**t000_.msa0.a3m**, and **t000_.msa0.ss2.a3m**, but it can't create   **t000_.atab**   so,I can't run third of this shell.
