### ISSUE TITLE
Example/pyrosetta/log/folding.stderr - No moduled named 'pyrosetta'

### ISSUE THREAD

**Issue by what-is-what** [RosettaCommons/RoseTTAFold#70]
I performed run_pyrosetta.sh using input.fa in example folder. 
However, I cannot understand why the folding.stderr in example folder(from github) states about pyrosetta is not imported. 
As I tried, it prints nothing(local). Also the score in modelQ.dat is absolutely different. I cannot understand which part is going wrong...

**Comment by ChrisLou-bioinfo** [comment]
6.Obtain a PyRosetta licence and install the package in the newly created folding conda environment (link).

**Comment by what-is-what** [comment]
I installed and in my case, it works well.
But, in this github example/pyrosetta/log/folding.stderr shows it cannot import pyrosetta, and has structure. 
I cannot understand this point.

**Comment by what-is-what** [comment]
> I installed and in my case, it works well.
> But, in this github example/pyrosetta/log/folding.stderr shows it cannot import pyrosetta, and has structure.
> I cannot understand this point.

Traceback (most recent call last):
  File "/mnt/home/minkbaek/git/RoseTTAFold/folding/RosettaTR.py", line 6, in <module>
    from utils import *
  File "/mnt/home/minkbaek/git/RoseTTAFold/folding/utils.py", line 5, in <module>
    from pyrosetta import *
ModuleNotFoundError: No module named 'pyrosetta'
Traceback (most recent call last):
  File "/mnt/home/minkbaek/git/RoseTTAFold/folding/RosettaTR.py", line 6, in <module>
    from utils import *
  File "/mnt/home/minkbaek/git/RoseTTAFold/folding/utils.py", line 5, in <module>
    from pyrosetta import *
ModuleNotFoundError: No module named 'pyrosetta'
Traceback (most recent call last):
  File "/mnt/home/minkbaek/git/RoseTTAFold/folding/RosettaTR.py", line 6, in <module>
    from utils import *
  File "/mnt/home/minkbaek/git/RoseTTAFold/folding/utils.py", line 5, in <module>
    from pyrosetta import *
ModuleNotFoundError: No module named 'pyrosetta'
Traceback (most recent call last):
  File "/mnt/home/minkbaek/git/RoseTTAFold/folding/RosettaTR.py", line 6, in <module>
    from utils import *
  File "/mnt/home/minkbaek/git/RoseTTAFold/folding/utils.py", line 5, in <module>
    from pyrosetta import *
ModuleNotFoundError: No module named 'pyrosetta'
Traceback (most recent call last):
  File "/mnt/home/minkbaek/git/RoseTTAFold/folding/RosettaTR.py", line 6, in <module>
    from utils import *
  File "/mnt/home/minkbaek/git/RoseTTAFold/folding/utils.py", line 5, in <module>
    from pyrosetta import *
ModuleNotFoundError: No module named 'pyrosetta'
Traceback (most recent call last):
  File "/mnt/home/minkbaek/git/RoseTTAFold/folding/RosettaTR.py", line 6, in <module>
    from utils import *
  File "/mnt/home/minkbaek/git/RoseTTAFold/folding/utils.py", line 5, in <module>
    from pyrosetta import *
ModuleNotFoundError: No module named 'pyrosetta'

**Comment by ChrisLou-bioinfo** [comment]
Yes，me too.

**Comment by aputron** [comment]
Did you install it within the `folding` folder?

**Comment by lj734999889** [comment]
Did you solve this problem?

**Comment by what-is-what** [comment]
> Did you solve this problem?

This was not my error, mine worked well, but the updated example shows that it has no pyrosetta. But I think this is not critical issue, so I closed.
