### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Wud1** [RosettaCommons/RoseTTAFold#96]
**I am running DAN-msa/pick_final_models.div.py and I get the following error** 

Traceback (most recent call last):
  File "/share/dev1fs1b/chenxl/software/anaconda3/envs/folding/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/share/dev1fs1b/chenxl/software/anaconda3/envs/folding/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/share/dev1fs1b/chenxl/RoseTTAFold/RoseTTAFold/DAN-msa/pick_final_models.div.py", line 72, in calc_lddt_dist
    lddt_1 = float(os.popen("%s/lddt/lddt -c %s %s | grep Glob"%(script_dir, pose_i, pose_j)).readlines()[-1].split()[-1])
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/share/dev1fs1b/chenxl/RoseTTAFold/RoseTTAFold/DAN-msa/pick_final_models.div.py", line 114, in <module>
    raw_dist = pool.map(calc_lddt_dist, args)
  File "/share/dev1fs1b/chenxl/software/anaconda3/envs/folding/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/share/dev1fs1b/chenxl/software/anaconda3/envs/folding/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
IndexError: list index out of range

How should this problem be solved? thanks you verv much

**Comment by Wud1** [comment]
/bin/sh: /share/dev1fs1b/chenxl/RoseTTAFold/RoseTTAFold/lddt/lddt: No such file or directory
/bin/sh: /share/dev1fs1b/chenxl/RoseTTAFold/RoseTTAFold/lddt/lddt: No such file or directory
/bin/sh: /share/dev1fs1b/chenxl/RoseTTAFold/RoseTTAFold/lddt/lddt: No such file or directory
/bin/sh: /share/dev1fs1b/chenxl/RoseTTAFold/RoseTTAFold/lddt/lddt: No such file or directory
/bin/sh: /share/dev1fs1b/chenxl/RoseTTAFold/RoseTTAFold/lddt/lddt: No such file or directory

**Comment by 275145** [comment]
> /bin/sh: /share/dev1fs1b/chenxl/RoseTTAFold/RoseTTAFold/lddt/lddt: No such file or directory /bin/sh: /share/dev1fs1b/chenxl/RoseTTAFold/RoseTTAFold/lddt/lddt: No such file or directory /bin/sh: /share/dev1fs1b/chenxl/RoseTTAFold/RoseTTAFold/lddt/lddt: No such file or directory /bin/sh: /share/dev1fs1b/chenxl/RoseTTAFold/RoseTTAFold/lddt/lddt: No such file or directory /bin/sh: /share/dev1fs1b/chenxl/RoseTTAFold/RoseTTAFold/lddt/lddt: No such file or directory

@Wud1 Have you solved this problem? I have the same problem, could you give me some advice?
